name: coverage
on: 
  pull_request_target:
    branches:
      - main
      - master
    types: [opened, reopened, synchronize]
  push:
    paths:
      - 'README.md'
      - '.github/workflows/coverage.yaml'
      - '**.js'
    branches:
      - main
      - 'release/**'
      - '!dev'
  workflow_dispatch:
jobs:
  coverage-report:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run test:coverage
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/clover.xml,./coverage/coverage-final.json,./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true