name: coverage
on: 
  pull_request:
    type: [opened, reopened, synchronize]
  push:
    paths:
      - 'README.md'
      - '**.yaml'
      - '!docs/**'
      - '**.js'
    branches:
      - 'main'
      - 'release/**'
      - '!dev'
  workflow_dispatch:
jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: npm install
      - uses: ArtiomTr/jest-coverage-report-action@v2