name: First workflow
on:
  push:
    paths:
      - 'README.md'
      - '**.yaml'
      - '!docs/**'
      - '**.js'
    branches:
      - 'main'
      - 'release/**'
      - '!dev'
  pull_request:
    branches:
      - 'main'
    types: [opened, reopened, synchronized, labeled, unlabeled]
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo Hello World
      - name: Find the current date
        run: |
          echo "TODAY=$(date +%y-%m-%d)" >> ${GITHUB_ENV}
      - name: Print the current date
        run: echo Hello World, today is $TODAY